[project]
name = "scratch-core"
version = "0.0.1"
description = "Scratch core libraries"
authors = [
  { name = "Netherlands Forensic Institute - CFS R&D Data", email = "cfs_rd_data@nfi.nl" },
  { name = "Sharlon N. Regales", email = "s.regales@nfi.nl" },
  { name = "Raymond Houwing", email = "r.houwing@nfi.nl" },
]
readme = "README.md"

dependencies = [
  "numpy>=2.3.4",
  "pillow>=12.0.0",
  "surfalize~=0.16.6",
  "x3p @ git+https://github.com/giacomomarchioro/pyx3p.git#81c0f764cf321e56dc41e9e3c71d14e97d5bc3ae",
]

[tool.ruff.lint.per-file-ignores]
"src/parsers/patches/*" = ["D103", "N806"]
