[project]
name = "stats"
version = "0.0.1"
description = "statistics"
authors = []
readme = "README.md"
dependencies = [
    "arviz>=0.22.0",
    "lir>=1.1.0",
    "pandas>=2.3.3",
    "pymc>=5.26.1",
]
