name: Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up shell environment
        uses: ./.github/actions/setup-devenv

      - name: Run checks
        run: devenv test

      - name: Check typing
        run: devenv shell just check-static

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up shell environment
        uses: ./.github/actions/setup-devenv

      - name: Run tests
        run: devenv shell just test xml

      - name: Compute diff coverage for PR
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          devenv shell just cov-diff

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          fail_below_min: true
          format: "markdown"
          output: "both"
          hide_branch_rate: false
          hide_complexity: true
          indicators: true

      - name: Add Coverage Difference PR Comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: diff-coverage
          recreate: true
          path: diff_coverage.md

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          header: global-coverage
          recreate: true
          path: code-coverage-results.md

  smoketests:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v5

      - name: Set up shell environment
        uses: ./.github/actions/setup-devenv

      - name: Run smoke tests (api.http requests)
        run: |
          devenv shell just api-bg
          devenv shell just smoke-test

  build_windows:
    runs-on: windows-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
      - uses: extractions/setup-just@v3

      - name: install dep
        run: just install

      - name: build artifact
        shell: bash
        run: just build

      - name: Run contract tests
        shell: bash
        run: |
          ./dist/main.exe &
          just smoke-test "main.exe"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: server
          path: ./dist/main.exe
