name: Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up shell environment
        uses: ./.github/actions/setup-devenv

      - name: Run checks
        run: devenv test

      - name: Check typing
        run: devenv shell just check-static

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up shell environment
        uses: ./.github/actions/setup-devenv

      - name: Run tests
        run: devenv shell just test xml

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          fail_below_min: true
          format: "markdown"
          output: "both"
          hide_branch_rate: false
          hide_complexity: true
          indicators: true

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md

  smoketests:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v5

      - name: Set up shell environment
        uses: ./.github/actions/setup-devenv

      - name: Run smoke tests (api.http requests)
        run: devenv shell just smoke-test
