name: manual_build.yaml

on:
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v6
      - uses: extractions/setup-just@v3
      - name: Check test resources
        shell: bash
        run: |
          ls -la packages/scratch-core/tests/resources/scans/circle.x3p
          file packages/scratch-core/tests/resources/scans/circle.x3p
      - name: Install dependencies
        run: just install

      - name: Build and test
        uses: ./.github/actions/build-api

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-artifact
          path: ./dist/main.exe
