name: Main

on:
  push:
    branches:
      - release
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
      - uses: extractions/setup-just@v3

      - name: install dep
        run: just install

      - name: build artifact
        shell: bash
        run: just build

      - name: Run contract tests
        shell: bash
        run: |
          ./dist/main.exe &
          just smoke-test "main.exe" ""

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: server
          path: ./dist/main.exe
