name: Release

on:
  release:
    types: [published]
jobs:
  release_windows:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
      - uses: extractions/setup-just@v3

      - name: install dep
        run: just install

      - name: Set up shell environment
        uses: ./.github/actions/build-api

      - name: Create GitHub Release and upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          body_path: ./scratch/release_notes.txt
          files: ./dist/main.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
